# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ERent' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ERent

    pod 'Kingfisher'
    pod 'Alamofire'
    pod 'XLPagerTabStrip'
    pod 'SVProgressHUD'

    pod 'IQKeyboardManagerSwift'
    pod 'Cosmos'
    
    pod 'Fabric'
    pod 'Crashlytics'
    
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
end
